# Generated by Django 5.1.2 on 2024-10-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collectorID", models.IntegerField()),
                ("issue", models.TextField()),
                ("userID", models.TextField()),
            ],
        ),
    ]
