# Generated by Django 5.1.2 on 2024-10-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userreport",
            name="user",
        ),
    ]
