# Generated by Django 5.1.2 on 2024-10-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0003_delete_collector_report_collector_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="collector_email",
        ),
        migrations.AddField(
            model_name="report",
            name="collector_telephone",
            field=models.CharField(default=88888888, max_length=255),
            preserve_default=False,
        ),
    ]
