# Generated by Django 5.1.2 on 2024-10-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0004_remove_report_collector_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="contacted",
            field=models.BooleanField(default=False),
        ),
    ]
