# Generated by Django 5.1.2 on 2024-10-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0005_report_contacted"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
