# Generated by Django 4.2.16 on 2024-10-10 12:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('termsAgreed', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('general', 'General'), ('collector', 'Collector'), ('regulator', 'Regulator')], default='general', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CollectorUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user')),
                ('collector_id', models.IntegerField(default=0)),
            ],
            bases=('user.user',),
        ),
    ]
