# Generated by Django 4.2.16 on 2024-10-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='collector_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('general', 'General'), ('collector', 'Collector'), ('regulator', 'Regulator')], default='general', max_length=10, null=True),
        ),
    ]
