# Generated by Django 4.2.16 on 2024-10-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='collector_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
