# Generated by Django 5.1.2 on 2024-10-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0002_ratings_delete_rating_alter_total_rating_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratings",
            name="userName",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
