# Generated by Django 5.1.2 on 2024-10-14 07:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0002_report_delete_reports"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Report",
            new_name="UserReport",
        ),
    ]
