# Generated by Django 5.1.2 on 2024-10-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0004_remove_ratings_userid_ratings_user_delete_userreport"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ratings",
            old_name="comment",
            new_name="comments",
        ),
        migrations.RemoveField(
            model_name="ratings",
            name="collectorID",
        ),
        migrations.AddField(
            model_name="ratings",
            name="collector_id",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
